### ISSUE TITLE
Pour le texte peut-etre que c'est mieux sans animation `infinite`

### ISSUE THREAD

**Issue by jnpn** [ValentinFootaine/stage#3]
https://github.com/ValentinFootaine/stage/blob/2800d457229d42e00fceca3bc2e21e7ef4d79998/index.css#L149

**Comment by jnpn** [comment]
Normalement faut pas faire un commit qui resout 2 issues a la fois. On en avait pas parle, mais en gros faut toujours isoler les modifications (comme ca on peut annuler un commit sans casser le reste). La comme c'est deja fait, tu peux cloturer cette issue aussi. J'te prepare des issues avec les trucs pour demain avec des liens.

**Comment by ValentinFootaine** [comment]
Ok je vois. Ahh cool tu gères.

**Comment by jnpn** [comment]
J'espere que c'est pas trop au passage. La j'ai mis 3 trucs, mais cool, tu prendras le temps de lire et d'aller a ton rythme.
