### ISSUE TITLE
Restructurer html

### ISSUE THREAD

**Issue by jnpn** [ValentinFootaine/stage#4]
il manque quelques trucs:

- doctype en premiere ligne (sinon les navigateurs se mettent dans un mode special retrocompatibilite avec les vieux sites)
  genre comme ici https://www.tutorialrepublic.com/html-tutorial/html-doctypes.php (au passage si tu peux mettre la langue "fr")
- tout ce qui est logo devrait etre dans une balise <header> ... </header> juste apres <body>
- le reste doit etre englobe dans une balise <main>

Apres j'te montrerais les variables CSS et aussi comment les modifier depuis la page (pour prototype le logo et les animations en live)

**Comment by ValentinFootaine** [comment]
Concernant le texte t'as raison ça rend mieux sans l'anim infinie. Après j'ai rajouté le doctype et le fr comme tu me l'as conseillé. En revanche j'ai pas saisi pour les balises, tu veux englober tout ce qui est svg dans une balise autre que <div>  du coup ? 

Dac tu me montrera ça demain en présentiel.

**Comment by jnpn** [comment]
Ah mais.. github efface les balises sans prevenir... 

- tout ce qui est logo devrait etre dans une balise `<header> ... </header>` juste apres `<body>`
- le reste doit etre englobe dans une balise `<main> ... </main>`

C'est probablement plus clair la.

**Comment by ValentinFootaine** [comment]
OKKK, de là venait la couille. J'avais du mal à saisir le sens de la phrase. Oui c'est plus clair, je m'occupe de changer ça et je le push de sorte à ce que tu le vois sur github.

**Comment by jnpn** [comment]
C'est rigolo apres coup ..

Quand t'as fini de refaire le html, fais un commit, et dans le message ajoute un mention "Fixes" comme explique ici https://github.blog/2013-01-22-closing-issues-via-commit-messages/ ca marquera cette issue/discussion comme cloturee. C'est le processus un peu standard pour regler les bugs etc sur github/gitlab.

la syntaxe c'est `Fixes #N` et N = numero de l'issue, ici c'est 4. (Je peux pas l'ecrire ici, je crains que github ferme l'issue direct)
